Repository onflow/flow-emulator, pull requests merged in 2021-12, with the labels that each got.

#101 Fix master and improve tests
  accounts_test.go
  block_info_test.go
  block_test.go
  collection_test.go
  convert/sdk/flow_test.go
  convert/vm_test.go
  events_test.go
  init_test.go
  logs_test.go
  pendingBlock_test.go
  script_test.go
  server/backend/backend_test.go
  server/liveness/check_test.go
  server/server.go
  storage/badger/changelog_test.go
  storage/badger/encoding_test.go
  storage/badger/keys_test.go
  storage/badger/store_test.go
  storage/memstore/memstore_test.go
  transaction_test.go
  types/result_test.go
Labels: Bugfix, Testing

#100 Release version 0.27.0
  accounts_test.go
  block_info_test.go
  block_test.go
  collection_test.go
  convert/sdk/flow_test.go
  convert/vm_test.go
  events_test.go
  go.mod
  go.sum
  init_test.go
  logs_test.go
  pendingBlock_test.go
  script_test.go
  server/backend/backend_test.go
  server/emulatorApi.go
  server/liveness/check_test.go
  server/server.go
  storage/badger/changelog_test.go
  storage/badger/encoding_test.go
  storage/badger/keys_test.go
  storage/badger/store_test.go
  storage/memstore/memstore_test.go
  transaction_test.go
  types/result_test.go
Labels: Release

#102 Embedding Storefront Contract
  server/contracts.go
  server/server.go
Labels: Bugfix

#108 Setting configuration service key
  blockchain.go
  cmd/emulator/start/start.go
  go.mod
  go.sum
  server/contracts.go
  server/server.go
Labels: Bugfix
