Repository onflow/flow-emulator, pull requests merged in 2022-06, with the labels that each got.

#157 Update to Secure Cadence (v0.24) and Go 1.18
  .github/workflows/ci.yml
  Makefile
  accounts_test.go
  block_info_test.go
  block_test.go
  blockchain.go
  cmd/emulator/Dockerfile
  collection_test.go
  events_test.go
  go.mod
  go.sum
  init_test.go
  pendingBlock_test.go
  script_test.go
  server/backend/mocks/emulator.go
  server/contracts.go
  storage/mocks/store.go
  transaction_test.go
Labels: Improvement, Developer Tool Team

#158 Update to Cadence v0.24.1
  go.mod
  go.sum
Labels: Improvement

#161 Update contracts
  go.mod
  go.sum
  server/contracts.go
  server/contracts/NFTStorefront.cdc
  server/server.go
  server/server_test.go
Labels: Bugfix
