Repository onflow/flow-emulator, pull requests merged in 2022-08, with the labels that each got.

#182 Storefront contract update
  go.mod
  go.sum
  server/contracts.go
  server/contracts/NFTStorefront.cdc
Labels: Improvement, Developer Tool Team

#187 Upgrade flow to v0.27.1
  .github/workflows/ci.yml
  Makefile
  accountStorage_test.go
  accounts_test.go
  block_info_test.go
  block_test.go
  collection_test.go
  emulator_test.go
  errors.go
  events_test.go
  go.mod
  go.sum
  init_test.go
  pendingBlock_test.go
  script_test.go
  server/backend/backend_test.go
  server/contracts.go
  server/emulator.go
  transaction_test.go
  types/result.go
  types/result_test.go
Labels: Improvement

#184 Fix parsing public and private key using the start command
  CONTRIBUTING.md
  Makefile
  README.md
  cmd/emulator/start/start.go
  docs/overview.md
  server/contracts.go
Labels: Bugfix, Developer Tool Team

#194 Update Cadence v0.26.0
  blockchain.go
  go.mod
  go.sum
  transaction_test.go
Labels: Improvement
