Repository onflow/flow-emulator, pull requests merged in 2023-02, with the labels that each got.

#311 Bump `flow-go` version
  blockchain.go
  go.mod
  go.sum
Labels: dependencies

#315 Create config endpoint
  server/emulator.go
Labels: Feature, Feedback

#294 Debugger (Debug Adapter Protocol)
  Makefile
  blockchain.go
  cmd/emulator/start/start.go
  go.mod
  go.sum
  server/backend/backend.go
  server/backend/emulator.go
  server/backend/mocks/emulator.go
  server/debugger/debugger.go
  server/debugger/debugsession.go
  server/emulator.go
  server/server.go
Labels: Feature

#317 Update Flow Go to v0.29.11
  blockchain.go
  go.mod
  go.sum
Labels: Improvement

#322 Prevent crashing on stop if listener wasn't initialized
  server/debugger/debugger.go
Labels: Bugfix
