Repository onflow/flow-emulator, pull requests merged in 2023-07, with the labels that each got.

#438 Transaction logs API endpoint
  emulator/blockchain.go
  emulator/emulator.go
  emulator/mocks/emulator.go
  server/utils/emulator.go
Labels: Feature

#439 Retire storage API
  adapters/sdk.go
  emulator/accountStorage_test.go
  emulator/blockchain.go
  emulator/emulator.go
  emulator/mocks/emulator.go
  go.mod
  server/server_test.go
  server/utils/emulator.go
  types/accountStorage.go
Labels: Improvement

#441 Auto block ticker fix
  emulator/blockTicker.go
Labels: Bugfix

#450 Docker Build Fix
  cmd/emulator/Dockerfile
Labels: Bugfix

#452 Remove FUSD references
  README.md
  docs/overview.md
  emulator/blockchain.go
  emulator/contracts.go
  go.mod
  go.sum
Labels: Improvement

#453 Add additional contracts to startup logs
  server/server.go
Labels: Improvement

#437 Basic pragma support ( sourceFile and debug )
  README.md
  adapters/access_test.go
  adapters/sdk_test.go
  check-headers.sh
  convert/flow_test.go
  docs/overview.md
  emulator/blockchain.go
  emulator/collection_test.go
  emulator/contracts.go
  emulator/contracts_test.go
  emulator/coverage_report_test.go
  emulator/emulator.go
  emulator/events_test.go
  emulator/init_test.go
  emulator/logs_test.go
  emulator/mocks/emulator.go
  emulator/pendingBlock.go
  emulator/pendingBlock_test.go
  emulator/pragma.go
  emulator/pragma_test.go
  emulator/script_test.go
  emulator/transaction_test.go
  server/debugger/debugsession.go
  server/server_test.go
Labels: Feature
