Repository onflow/flow-emulator, pull requests merged in 2023-05, with the labels that each got.

#364 Update flowgo version
  blockchain.go
  go.mod
  go.sum
  pendingBlock.go
  server/backend/adapter.go
  server/grpc.go
  storage/memstore/memstore.go
  storage/memstore/memstore_test.go
  storage/mocks/store.go
  storage/store.go
  storage/store_test.go
Labels: Improvement

#365 Rollback ledger and tests
  storage/sqlite/store.go
  transaction_test.go
Labels: Bugfix

#380 Create nightly builds
  .github/workflows/nightly-builds.yml
Labels: Improvement

#383 Fix documentation of a flag
  README.md
  cmd/emulator/start/start.go
Labels: Documentation
