Repository onflow/flow-emulator, pull requests merged in 2023-06, with the labels that each got.

#393 Update to Cadence v0.39.1
  emulator/blockchain.go
  emulator/coverage_reported_runtime.go
  emulator/emulator.go
  emulator/mocks/emulator.go
  go.mod
  go.sum
  server/debugger/debugsession.go
Labels: Improvement

#394 Simplify configuration for coverage reporting
  emulator/blockchain.go
  server/server.go
Labels: Improvement

#395 Remove redundant if assignment with direct `runtime.Config` field assignment
  emulator/blockchain.go
Labels: Improvement

#408 Replace JSON-CDC with CCF for events
  convert/flow.go
  go.mod
  go.sum
  storage/encoding_test.go
  storage/store_test.go
Labels: Feature

#409 Update to latest Go SDK and flow-go
  go.mod
  go.sum
  storage/remote/store_test.go
Labels: Improvement

#410 Enable capability controllers
  emulator/blockchain.go
Labels: Feature

#412 Convert CCF to json-cdc in access adapter
  adapters/access.go
  adapters/access_test.go
Labels: Bugfix

#411 Add tests for Cadence features behind a feature flag
  emulator/accountlinking_test.go
  emulator/attachments_test.go
  emulator/capcons_test.go
Labels: Improvement

#413 Update to Cadence v0.39.3
  go.mod
  go.sum
Labels: Improvement

#416 Add tests for latest regressions
  emulator/contracts_test.go
  emulator/coverage_report_test.go
  server/server.go
  server/server_test.go
Labels: Improvement

#417 Logging fix for Access API
  adapters/access.go
  emulator/blockchain.go
  utils/logging.go
Labels: Bugfix

#419 Update to Cadence 0.39.8 and use CCF events mode to fix field order compatibility
  adapters/access_test.go
  convert/flow.go
  emulator/accountlinking_test.go
  emulator/events_test.go
  emulator/transaction_test.go
  go.mod
  go.sum
Labels: Improvement, Bugfix

#422 Add support for specifying start height in forked mode
  README.md
  cmd/emulator/start/start.go
  docs/overview.md
  emulator/blockchain.go
  server/server.go
  storage/remote/store.go
Labels: Feature

#432 Enable persistent storage in forked mode
  README.md
  docs/overview.md
  server/server.go
  storage/remote/store.go
  storage/remote/store_test.go
  storage/sqlite/store.go
  storage/util/defaultStore.go
Labels: Feature

#431 Implement GetTransaction*ByBlockID
  adapters/access.go
  emulator/blockchain.go
  emulator/transaction_test.go
Labels: Improvement

#434 Auto update to onflow/cadence v0.39.12
  go.mod
  go.sum
Labels: Improvement

#429 Add REST API metrics to /metrics
  go.mod
  server/access/rest.go
Labels: Improvement

#427 Contracts flag - monotonic chain support
  emulator/contracts.go
  emulator/contracts_test.go
  server/server.go
Labels: Bugfix

#430 Fix StatusCode on transaction result
  emulator/blockchain.go
Labels: Bugfix

#428 update NFT Contract, deploy ViewResolver from Metadata
  emulator/contracts.go
  go.mod
  go.sum
Labels: Feature
