Repository onflow/flow-emulator, pull requests merged in 2023-11, with the labels that each got.

#503 Bump `flow-go` and remove replace
  go.mod
  go.sum
Labels: dependencies

#504 Auto update to onflow/cadence v0.42.5
  go.mod
  go.sum
Labels: Improvement

#496 REST API streaming support
  emulator/blockchain.go
  server/access/rest.go
  server/access/streamBackend.go
  server/server.go
Labels: Feature

#510 EVM proof of concept
  README.md
  cmd/emulator/start/start.go
  emulator/accounts_test.go
  emulator/blockchain.go
  emulator/coverage_report_test.go
  emulator/script_test.go
  go.mod
  go.sum
  server/server.go
Labels: Feature
