Repository onflow/flow-emulator, pull requests merged in 2023-04, with the labels that each got.

#347 Update flow-go version
  go.mod
  go.sum
  transaction_test.go
Labels: Improvement

#351 Convert Cadence logs to realtime
  blockchain.go
  server/backend/backend.go
  server/server.go
Labels: Improvement

#349 Update pending block to execute transactions using vm.RunV2
  blockchain.go
  convert/emu.go
  convert/vm.go
  convert/vm_test.go
  pendingBlock.go
Labels: Improvement

#360 Enable attachments
  blockchain.go
Labels: Feature

#361 Rollback docs and height limit check fix
  README.md
  docs/overview.md
  storage/sqlite/store.go
Labels: Bugfix, Documentation
