Repository onflow/flow-emulator, pull requests merged in 2024-05, with the labels that each got.

#654 Update to Cadence v1.0.0-preview.24
  adapters/access_test.go
  adapters/sdk.go
  emulator/blockchain_test.go
  emulator/events_test.go
  emulator/transaction_test.go
  go.mod
  go.sum
  server/debugger/debugsession.go
Labels: dependencies

#659 Update to Cadence v1.0.0-preview.25
  go.mod
  go.sum
Labels: dependencies

#660 Change nightly build go version to v1.21.9
  .github/workflows/nightly-builds.yml
Labels: Bugfix

#678 Update to Cadence v1.0.0-preview.29
  go.mod
  go.sum
  storage/migration/cadence1.go
  storage/migration/cadence1_test.go
Labels: dependencies

#681 Add get full collection support
  adapters/access.go
  emulator/blockchain.go
  emulator/emulator.go
  emulator/mocks/emulator.go
  storage/memstore/memstore.go
  storage/mocks/store.go
  storage/store.go
  storage/store_test.go
  utils/unittest/fixtures.go
Labels: Improvement
