Repository onflow/flow-emulator, pull requests merged in 2024-07, with the labels that each got.

#682 Add empty node version info response
  adapters/access.go
  adapters/access_test.go
Labels: Improvement

#708 Update to Cadence v1.0.0-preview.37
  emulator/transaction_test.go
  go.mod
  go.sum
Labels: dependencies

#713 Update readme docs for emulating testnet mainnet
  README.md
Labels: Documentation

#712 Changed key index type to uint32
  adapters/access.go
  convert/flow.go
  emulator/accounts_test.go
  emulator/emulator.go
  emulator/transaction_test.go
  go.mod
  go.sum
  internal/mocks/access.go
  internal/mocks/executiondata.go
Labels: Improvement

#716 Update flow-go to v0.36.2
  go.mod
  go.sum
Labels: Improvement, dependencies

#717 Add support for `EVM.heartbeat` resource on system chunk transaction
  emulator/blockchain.go
  emulator/templates/systemChunkTransactionTemplate.cdc
  server/access/streamBackend.go
  storage/migration/cadence1_test.go
Labels: Improvement
