Repository onflow/flow-emulator, pull requests merged in 2024-03, with the labels that each got.

#598 Update Flow Go SDK to v0.46.0
  go.mod
  go.sum
Labels: dependencies

#600 Port Dockerfile build to `release/v0`
  cmd/emulator/Dockerfile
  cmd/emulator/Dockerfile.relic
Labels: Improvement

#601 Fix flag typo
  cmd/emulator/Dockerfile
Labels: Bugfix

#602 fix typo in Dockerfile
  cmd/emulator/Dockerfile
Labels: Bugfix

#594 Reenable forked mainnet
  Makefile
  README.md
  adapters/access.go
  adapters/access_test.go
  adapters/sdk_test.go
  cmd/emulator/start/start.go
  docs/overview.md
  emulator/mocks/emulator.go
  go.mod
  go.sum
  internal/access.go
  internal/executiondata.go
  server/server.go
  storage/memstore/memstore_test.go
  storage/mocks/store.go
  storage/remote/store.go
  storage/sqlite/store.go
  storage/store.go
  storage/store_test.go
Labels: Feature, Improvement

#611 Fix CI/tests from previous merge
  adapters/access_test.go
  emulator/mocks/emulator.go
  internal/access.go
  internal/executiondata.go
  storage/mocks/store.go
Labels: Bug

#603 Reenable forked mainnet
  Makefile
  README.md
  adapters/access.go
  adapters/access_test.go
  adapters/sdk_test.go
  cmd/emulator/start/start.go
  docs/overview.md
  emulator/mocks/emulator.go
  go.mod
  go.sum
  internal/access.go
  internal/executiondata.go
  server/server.go
  storage/memstore/memstore_test.go
  storage/mocks/store.go
  storage/remote/store.go
  storage/sqlite/store.go
  storage/store.go
  storage/store_test.go
Labels: Feature, Improvement
